#!/bin/python3

"""pcmd - portable executor of arbitrary command(s)

Usage:
    pcmd    [--version] [--help]
            <module> [<args>...]

Modules:
    master      master server module
    slave       slave  server module
    config      configuration module

Options:
    --help      Show this screen
    --version   Show version

"""

import sys

import docopt

import common.logger

import master.master
import master.main

import config.main

from common.const import ModuleType
import config.configuration


def main(conf):
    if conf.module is ModuleType.MASTER:
        return master.main.main(conf)

    elif conf.module is ModuleType.SLAVE:
        return None

    elif conf.module is ModuleType.CONFIG:
        return config.main.main(conf)


if __name__ == '__main__':
    cliArgs = docopt.docopt(
        __doc__,
        version=common.const.version,
        options_first=True,
    )

    logger = common.logger.get_logger('pcmd', True)

    try:
        conf_main = config.configuration.Configuration(cliArgs)
    except config.configuration.ModuleNotFound:
        docopt.docopt(
            __doc__,
            argv='--help'
        )
        sys.exit(0)

    sys.exit(main(conf_main))
