#!/bin/python3

"""pcmd - portable executor of arbitrary command(s)

Usage:
    pcmd -h | --help
    pcmd master
        start
            [-a | --attach]
            [-v | --verbose]
    pcmd master
        stop
            [-v | --verbose]
    pcmd slave
        start
            [-a | --attach]
            [-v | --verbose]
    pcmd slave
        stop
            [-v | --verbose]
    pcmd config
        set <name> <value>
    pcmd config
        get <name>
    pcmd config
        remove <name>
    pcmd --version

Options:
    -a, --attach    Attach server start to the console
    -v, --verbose   More detailed logs

    -h --help   Show this screen
    --version   Show version
"""

import sys

import docopt

import common.logger

import master.main
import master.master

import slave

import config.main


def main(cli_args):
    if cli_args['master']:
        master_root = master.master.Master(cli_args)
        return master.main.main(master_root)
    elif cli_args['slave']:
        return slave.main(cli_args)
    elif cli_args['config']:
        return config.main.main(cli_args)
    else:
        raise Exception("Not Implemented")


if __name__ == '__main__':
    cliArgs = docopt.docopt(
        __doc__,
        version='pcmd {}'.format(common.const.app['VERSION'])
    )
    logger = common.logger.get_logger('pcmd', cliArgs['--verbose'])

    sys.exit(main(cliArgs))
